@startgantt GanttChart
Project starts 2026-02-16

' Détail des zones a exclure du temps de travail (vacances / CF / autres obligations)
' syntaxe  : {date} is closed / {date} to {date} is closed
    
    ' Vacances d'hiver
    2026-02-28 to 2026-03-8 is closed

    ' vacances de printemps
    2026-04-18 to 2026-05-04 is closed

    ' Obligations Loup

    ' Obligations Antonin

' Fin

' Detail des taches à effectuer, syntaxe ci-dessous : 
'   * -- Categorie -- 
'   * [nom de la tâche] requires/lasts X days/weeks
'   * possibilité de coloriser avec "and is colored in {couleur}" (les mots clés des couleurs sont préshot par l'extension PlantUML)
-- Gestion de Projet & Livrables Cassiopée--  
[Plannification] requires 5 days and is colored in SkyBlue

-- Interface -- 
[Doc Interface] requires 12 days and is colored in IndianRed
[Tests QML] requires 10 days
[Vue Listing] requires 1 week
[Vue Details] requires 3 week

-- Traitement des données -- 
[Doc données] requires 1 weeks and is colored in IndianRed
[Tests libdive] requires 1 weeks
[Récupération données] requires 5 days
[Wrapper] requires 5 days

-- Intégration --
[Integration Listing] requires 2 weeks
[Integration Details] requires 3 weeks

' Fin du détail des tâches

'------------------------------------------------------------

' Détail des dates de début/fin
'   * [nom de la tache] starts at {date}
'   * une date peut être la fin d'un évenement ("X's end") ou son debut ("X's start")

[Plannification] starts at 2026-02-16

' Phase doc et tests
[Doc données] starts at 2026-02-16
[Tests libdive] starts at [Doc données]'s end

[Doc Interface] starts at 2026-02-16
[Tests QML] starts at [Doc Interface]'s end

' Phase developpement
[Vue Listing] starts at [Tests QML]'s end
[Vue Details] starts at [Vue Listing]'s end

[Récupération données] starts at [Tests libdive]'s end
[Wrapper] starts at [Récupération données]'s end

'Phase intégration interface / back-end

[Integration Listing] starts at [Wrapper]'s end
[Integration Listing] starts at [Vue Listing]'s end
[Integration Details] starts at [Wrapper]'s end
[Integration Details] starts at [Vue Details]'s end

' Fin du détail des dates
@endgantt
